### ISSUE TITLE
star light secondary color stuck on #00ff00

### ISSUE THREAD

**Issue by miromonti** [BlitzKraig/fvtt-CommunityLighting#31]
![image](https://user-images.githubusercontent.com/38819125/110884976-da102e00-829a-11eb-9ede-af5561aa8fb1.png)

No matter how often I change the color, any color I choose, and with all other mods turned off, Star Light's secondary color reverts to #00ff00. Is this just me? Is there a conflict I should know about?

**Comment by BlitzKraig** [comment]
Hmm, that's definintely not right. I'll take a look when I'm working on the CL improvements

Thanks for the feedback!

**Comment by miromonti** [comment]
Update: Turns out the secondary color sticks when adjusting the _on-scene_ token's vision. Secondary color _via the character sheet_ is what reverts to #00ff00. So, not the worst thing; just the inconvenience of having to adjust the Star Light secondary color each time I place a token onto scene.

**Comment by miromonti** [comment]
Just discovered this issue also affects Star Light Disco. Don't know whether that's always been the case, but I suppose yes, given their similarity.

**Comment by miromonti** [comment]
No rush. I've learned to work around the issue. I look forward to your fix.

**Comment by BlitzKraig** [comment]
Hey, just so you know, this issue should be fixed in the foundry 0.8+ version of Community Lighting.

Let me know if you're having any issues with it

**Comment by miromonti** [comment]
Thanks for the update! Just so I'm clear, the issue is fixed for Foundry 0.8+, but remains for 0.7.x, correct?

**Comment by BlitzKraig** [comment]
Correct, it is likely still an issue in the final 0.7 update.

Depending on request volume, I may push a fix for 0.7, but doesn't seem worth it since most will be moving, or have already moved, to 0.8
